spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "[classpath:/, classpath:/config, classpath:/config/{application}]"
server:
  port: ${CONFIG_PORT:8888}

management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true